server:
  port: 8000

spring:
  application:
    name: client-goods #此实例注册到eureka服务端的name 集群时需保持一致

eureka:
  client:
    service-url:
      #eureka服务端提供的注册地址 参考服务端配置的这个路
      defaultZone: http://192.168.0.110:3000/eureka,http://192.168.0.110:3001/eureka,http://192.168.0.110:3002/eureka
  instance:
    instance-id: goods-0 #此实例注册到eureka服务端的唯一的实例名称
    prefer-ip-address: true #是否显示IP地址
    #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    lease-renewal-interval-in-seconds: 30
    #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    lease-expiration-duration-in-seconds: 90